[package]
name = "dwfv"
version = "0.4.1"
description = "A simple digital waveform viewer with vi-like key bindings"
authors = ["Pierre Surply <pierre.surply@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/psurply/dwfv"
edition = "2018"

keywords = ["eda", "vcd"]
categories = [
    "command-line-utilities",
    "development-tools::debugging",
    "embedded",
    "parsing",
    "visualization"
]

exclude = [
    "examples"
]

[badges]
travis-ci = { repository = "psurply/dwfv" }

[dependencies]
gumdrop = "0.8"
nom = { version = "7", default-features = false, features = ["std"] }
tui = "0.16"
termion = "1.5"
